name: Docker Image CI

on:
  push:
    branches: [ "add-CI-for-image-builds" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name:
      run: ls -lsa
      
    - name: Build the Docker image for dApp
      run: docker build . --file dapp/docker/Dockerfile --tag swapscope-dapp:$(date +%s)
